paths:
  static: public
  uploads: public/uploads
timezone: Asia/Bangkok
markdown:
  engine: commonmark
  options: {}
collections_config:
  pages:
    path: ''
    icon: wysiwyg
  public_admin:
    path: public/admin
    icon: public_off
